/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.frames;
import static Controller.LinkManager.Dashboard;
import static Controller.LinkManager.Edit;
import static Controller.LinkManager.Quit;
import static Controller.LinkManager.SearchRecord;
import static Controller.LinkManager.ViewAll;
import static Controller.LinkManager.ViewCourse;
import static Controller.LinkManager.ViewReport;
import view.custom.scrollbar.ScrollBarCustom;

/**
 *
 * @author rolen
 */
public class Add_fees extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Add_fees() {
        initComponents();
        
        scroll.setVerticalScrollBar(new ScrollBarCustom());
        
        lbl_cheque.setVisible(false);
        lbl_bank.setVisible(false);
        
        txt_cheque.setVisible(false);
        txt_bank.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        sidebar = new test.RoundPanel();
        side_logo = new javax.swing.JLabel();
        btn_dash = new button.Button();
        add_fees = new button.Button();
        search_records = new button.Button();
        view_all_records = new button.Button();
        edit_course = new button.Button();
        view_courses = new button.Button();
        view_report = new button.Button();
        btn_logout = new button.Button();
        inner_panel = new test.RoundPanel();
        Add_fees = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        workng_panel = new javax.swing.JPanel();
        lbl_rno = new javax.swing.JLabel();
        txt_receipt_no = new textfield.TextField();
        top_date = new javax.swing.JLabel();
        txt_tdate = new textfield.TextField();
        btn_tdate = new button.Button();
        PAN = new javax.swing.JLabel();
        lbl_pmode = new javax.swing.JLabel();
        payment_means = new view.custom.Combobox();
        lbl_cheque = new javax.swing.JLabel();
        txt_cheque = new textfield.TextField();
        lbl_bank = new javax.swing.JLabel();
        txt_bank = new textfield.TextField();
        lbl_rfrom = new javax.swing.JLabel();
        txt_received_from = new textfield.TextField();
        payment_lbl = new javax.swing.JLabel();
        s_year = new textfield.TextField();
        to = new javax.swing.JLabel();
        e_year = new textfield.TextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        SN = new javax.swing.JLabel();
        Courses = new javax.swing.JLabel();
        Amount = new javax.swing.JLabel();
        txt_course = new textfield.TextField();
        txt_Amount = new textfield.TextField();
        txt_vat = new textfield.TextField();
        txt_sc_amt = new textfield.TextField();
        vat = new javax.swing.JLabel();
        sc_amt = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        total = new javax.swing.JLabel();
        txt_total = new textfield.TextField();
        In_Words = new javax.swing.JLabel();
        txt_in_words = new textfield.TextField();
        remarks = new javax.swing.JLabel();
        btn_print = new button.Button();
        sign = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        textAreaScroll1 = new view.custom.textarea.TextAreaScroll();
        textArea1 = new view.custom.textarea.TextArea();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_panel.setBackground(new java.awt.Color(62, 62, 62));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(82, 82, 82));
        sidebar.setRoundBottomRight(50);
        sidebar.setRoundTopRight(50);
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/dash_logo.png"))); // NOI18N
        sidebar.add(side_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 230, 120));

        btn_dash.setBackground(new java.awt.Color(82, 82, 82));
        btn_dash.setForeground(new java.awt.Color(252, 252, 252));
        btn_dash.setText("Dashboard");
        btn_dash.setFont(new java.awt.Font("Noto Sans", 1, 44)); // NOI18N
        btn_dash.setShadowColor(new java.awt.Color(82, 82, 82));
        btn_dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashActionPerformed(evt);
            }
        });
        sidebar.add(btn_dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        add_fees.setBackground(new java.awt.Color(214, 173, 87));
        add_fees.setForeground(new java.awt.Color(65, 65, 65));
        add_fees.setText("Add Fees");
        add_fees.setFont(new java.awt.Font("Droid Sans", 1, 36)); // NOI18N
        add_fees.setRound(60);
        sidebar.add(add_fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 330, 70));

        search_records.setBackground(new java.awt.Color(65, 65, 65));
        search_records.setForeground(new java.awt.Color(214, 173, 87));
        search_records.setText("Search Records");
        search_records.setFont(new java.awt.Font("Droid Sans", 1, 36)); // NOI18N
        search_records.setRound(60);
        search_records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_recordsActionPerformed(evt);
            }
        });
        sidebar.add(search_records, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 330, 70));

        view_all_records.setBackground(new java.awt.Color(65, 65, 65));
        view_all_records.setForeground(new java.awt.Color(214, 173, 87));
        view_all_records.setText("View all Records");
        view_all_records.setFont(new java.awt.Font("Droid Sans", 1, 36)); // NOI18N
        view_all_records.setRound(60);
        view_all_records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_all_recordsActionPerformed(evt);
            }
        });
        sidebar.add(view_all_records, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 330, 70));

        edit_course.setBackground(new java.awt.Color(65, 65, 65));
        edit_course.setForeground(new java.awt.Color(214, 173, 87));
        edit_course.setText("Edit Course");
        edit_course.setFont(new java.awt.Font("Droid Sans", 1, 36)); // NOI18N
        edit_course.setRound(60);
        edit_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_courseActionPerformed(evt);
            }
        });
        sidebar.add(edit_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 330, 70));

        view_courses.setBackground(new java.awt.Color(65, 65, 65));
        view_courses.setForeground(new java.awt.Color(214, 173, 87));
        view_courses.setText("View Courses");
        view_courses.setFont(new java.awt.Font("Droid Sans", 1, 36)); // NOI18N
        view_courses.setRound(60);
        view_courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_coursesActionPerformed(evt);
            }
        });
        sidebar.add(view_courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 710, 330, 70));

        view_report.setBackground(new java.awt.Color(65, 65, 65));
        view_report.setForeground(new java.awt.Color(214, 173, 87));
        view_report.setText("View Report");
        view_report.setFont(new java.awt.Font("Droid Sans", 1, 36)); // NOI18N
        view_report.setRound(60);
        view_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_reportActionPerformed(evt);
            }
        });
        sidebar.add(view_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 790, 330, 70));

        btn_logout.setBackground(new java.awt.Color(120, 120, 120));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logout.png"))); // NOI18N
        btn_logout.setRound(100);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        sidebar.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 890, 110, 100));

        main_panel.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 1050));

        inner_panel.setBackground(new java.awt.Color(62, 62, 62));
        inner_panel.setRoundBottomLeft(40);
        inner_panel.setRoundBottomRight(40);
        inner_panel.setRoundTopLeft(40);
        inner_panel.setRoundTopRight(40);
        inner_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add_fees.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        Add_fees.setText("Add Fees");
        inner_panel.add(Add_fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        workng_panel.setBackground(new java.awt.Color(62, 62, 62));
        workng_panel.setForeground(new java.awt.Color(183, 183, 183));
        workng_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_rno.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        lbl_rno.setText("Receipt no.");
        workng_panel.add(lbl_rno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        txt_receipt_no.setEditable(false);
        txt_receipt_no.setBackground(new java.awt.Color(95, 95, 95));
        txt_receipt_no.setForeground(new java.awt.Color(183, 183, 183));
        txt_receipt_no.setShadowColor(new java.awt.Color(254, 254, 254));
        workng_panel.add(txt_receipt_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 190, -1));

        top_date.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        top_date.setText("Date:");
        workng_panel.add(top_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, -1, -1));

        txt_tdate.setEditable(false);
        txt_tdate.setBackground(new java.awt.Color(95, 95, 95));
        txt_tdate.setForeground(new java.awt.Color(183, 183, 183));
        txt_tdate.setShadowColor(new java.awt.Color(254, 254, 254));
        workng_panel.add(txt_tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 180, -1));

        btn_tdate.setBackground(new java.awt.Color(95, 95, 95));
        btn_tdate.setForeground(new java.awt.Color(183, 183, 183));
        btn_tdate.setText("...");
        btn_tdate.setRound(20);
        btn_tdate.setShadowColor(new java.awt.Color(254, 254, 254));
        workng_panel.add(btn_tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 40, -1));

        PAN.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        PAN.setText("GSTIN: 0000000");
        workng_panel.add(PAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 200, -1));

        lbl_pmode.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        lbl_pmode.setText("Mode of Payment");
        workng_panel.add(lbl_pmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 30));

        payment_means.setBackground(new java.awt.Color(65, 65, 65));
        payment_means.setForeground(new java.awt.Color(255, 226, 57));
        payment_means.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Bank", "Online Payment" }));
        payment_means.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_meansActionPerformed(evt);
            }
        });
        workng_panel.add(payment_means, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 210, 60));

        lbl_cheque.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        lbl_cheque.setText("Cheque no.");
        workng_panel.add(lbl_cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        txt_cheque.setBackground(new java.awt.Color(95, 95, 95));
        txt_cheque.setForeground(new java.awt.Color(183, 183, 183));
        txt_cheque.setShadowColor(new java.awt.Color(254, 254, 254));
        txt_cheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chequeActionPerformed(evt);
            }
        });
        workng_panel.add(txt_cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 350, -1));

        lbl_bank.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        lbl_bank.setText("Bank Name");
        workng_panel.add(lbl_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        txt_bank.setBackground(new java.awt.Color(95, 95, 95));
        txt_bank.setForeground(new java.awt.Color(183, 183, 183));
        txt_bank.setShadowColor(new java.awt.Color(254, 254, 254));
        workng_panel.add(txt_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 350, -1));

        lbl_rfrom.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        lbl_rfrom.setText("Received From");
        workng_panel.add(lbl_rfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        txt_received_from.setBackground(new java.awt.Color(95, 95, 95));
        txt_received_from.setForeground(new java.awt.Color(183, 183, 183));
        txt_received_from.setShadowColor(new java.awt.Color(254, 254, 254));
        workng_panel.add(txt_received_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 300, -1));

        payment_lbl.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        payment_lbl.setText("The following payment for college for the year");
        workng_panel.add(payment_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 440, -1));

        s_year.setBackground(new java.awt.Color(95, 95, 95));
        s_year.setForeground(new java.awt.Color(183, 183, 183));
        s_year.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s_year.setText("2022");
        s_year.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        workng_panel.add(s_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 70, -1));

        to.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        to.setText("to");
        workng_panel.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        e_year.setBackground(new java.awt.Color(95, 95, 95));
        e_year.setForeground(new java.awt.Color(183, 183, 183));
        e_year.setText("2023");
        e_year.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        e_year.setShadowColor(new java.awt.Color(254, 254, 254));
        e_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_yearActionPerformed(evt);
            }
        });
        workng_panel.add(e_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(95, 95, 95));
        workng_panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 1110, 10));

        jSeparator2.setForeground(new java.awt.Color(95, 95, 95));
        workng_panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 1110, 10));

        SN.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        SN.setText("SN");
        workng_panel.add(SN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        Courses.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        Courses.setText("Courses");
        workng_panel.add(Courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        Amount.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        Amount.setText("Amount");
        workng_panel.add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, -1, -1));

        txt_course.setBackground(new java.awt.Color(95, 95, 95));
        txt_course.setForeground(new java.awt.Color(183, 183, 183));
        txt_course.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        txt_course.setShadowColor(new java.awt.Color(254, 254, 254));
        workng_panel.add(txt_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 480, -1));

        txt_Amount.setBackground(new java.awt.Color(95, 95, 95));
        txt_Amount.setForeground(new java.awt.Color(183, 183, 183));
        txt_Amount.setShadowColor(new java.awt.Color(254, 254, 254));
        workng_panel.add(txt_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 130, -1));

        txt_vat.setBackground(new java.awt.Color(95, 95, 95));
        txt_vat.setForeground(new java.awt.Color(183, 183, 183));
        txt_vat.setShadowColor(new java.awt.Color(254, 254, 254));
        workng_panel.add(txt_vat, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, 130, -1));

        txt_sc_amt.setBackground(new java.awt.Color(95, 95, 95));
        txt_sc_amt.setForeground(new java.awt.Color(183, 183, 183));
        txt_sc_amt.setShadowColor(new java.awt.Color(254, 254, 254));
        workng_panel.add(txt_sc_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 130, -1));

        vat.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        vat.setText("VAT %");
        workng_panel.add(vat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, -1));

        sc_amt.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        sc_amt.setText("Scholarship Amount");
        workng_panel.add(sc_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(95, 95, 95));
        workng_panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 1110, 10));

        total.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        total.setText("Total:");
        workng_panel.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 670, -1, -1));

        txt_total.setBackground(new java.awt.Color(95, 95, 95));
        txt_total.setForeground(new java.awt.Color(183, 183, 183));
        txt_total.setShadowColor(new java.awt.Color(254, 254, 254));
        workng_panel.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 660, 140, -1));

        In_Words.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        In_Words.setText("In Words:");
        workng_panel.add(In_Words, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 750, -1, -1));

        txt_in_words.setBackground(new java.awt.Color(95, 95, 95));
        txt_in_words.setForeground(new java.awt.Color(183, 183, 183));
        txt_in_words.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        txt_in_words.setShadowColor(new java.awt.Color(254, 254, 254));
        workng_panel.add(txt_in_words, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 740, 560, -1));

        remarks.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        remarks.setText("Remarks:");
        workng_panel.add(remarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 850, -1, -1));

        btn_print.setBackground(new java.awt.Color(255, 226, 57));
        btn_print.setText("Print");
        btn_print.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        btn_print.setRound(40);
        workng_panel.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 1000, 120, 50));

        sign.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        sign.setText("Receiver's Signature");
        workng_panel.add(sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 920, -1, -1));
        workng_panel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 900, 210, 10));

        textAreaScroll1.setBackground(new java.awt.Color(95, 95, 95));
        textAreaScroll1.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        textAreaScroll1.setLineColor(new java.awt.Color(255, 226, 57));

        textArea1.setBackground(new java.awt.Color(95, 95, 95));
        textArea1.setColumns(20);
        textArea1.setForeground(new java.awt.Color(183, 183, 183));
        textArea1.setRows(5);
        textArea1.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        textAreaScroll1.setViewportView(textArea1);

        workng_panel.add(textAreaScroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 840, 560, 110));

        scroll.setViewportView(workng_panel);

        inner_panel.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1180, 730));

        main_panel.add(inner_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 1220, 850));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        bg.setText("background");
        main_panel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 1480, 1050));

        getContentPane().add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_chequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chequeActionPerformed

    private void payment_meansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_meansActionPerformed
        if(payment_means.getSelectedIndex()==1){
            txt_cheque.setVisible(true);
            lbl_cheque.setVisible(true);
            lbl_bank.setVisible(true);
            txt_bank.setVisible(true);
        }
        
        if((payment_means.getSelectedIndex()==0 )|| (payment_means.getSelectedIndex()==2 )){
            txt_cheque.setVisible(false);
            lbl_cheque.setVisible(false);
            lbl_bank.setVisible(false);
            txt_bank.setVisible(false);
        }
    }//GEN-LAST:event_payment_meansActionPerformed

    private void e_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_yearActionPerformed

    private void btn_dashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashActionPerformed
    Dashboard();
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btn_dashActionPerformed

    private void search_recordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_recordsActionPerformed
    SearchRecord();
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_search_recordsActionPerformed

    private void view_all_recordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_all_recordsActionPerformed
    ViewAll();
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_view_all_recordsActionPerformed

    private void edit_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_courseActionPerformed
    Edit();
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_edit_courseActionPerformed

    private void view_coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_coursesActionPerformed
    ViewCourse();
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_view_coursesActionPerformed

    private void view_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_reportActionPerformed
    ViewReport();
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_view_reportActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
    Quit();          // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Add_fees object= new Add_fees();
        object.cash();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_fees().setVisible(true);
            }
        });
    }
    public void cash(){
        lbl_cheque.setVisible(false);
        lbl_bank.setVisible(false);
        
        txt_cheque.setVisible(false);
        txt_bank.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_fees;
    private javax.swing.JLabel Amount;
    private javax.swing.JLabel Courses;
    private javax.swing.JLabel In_Words;
    private javax.swing.JLabel PAN;
    private javax.swing.JLabel SN;
    private button.Button add_fees;
    private javax.swing.JLabel bg;
    private button.Button btn_dash;
    private button.Button btn_logout;
    private button.Button btn_print;
    private button.Button btn_tdate;
    private textfield.TextField e_year;
    private button.Button edit_course;
    private test.RoundPanel inner_panel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_bank;
    private javax.swing.JLabel lbl_cheque;
    private javax.swing.JLabel lbl_pmode;
    private javax.swing.JLabel lbl_rfrom;
    private javax.swing.JLabel lbl_rno;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel payment_lbl;
    private view.custom.Combobox payment_means;
    private javax.swing.JLabel remarks;
    private textfield.TextField s_year;
    private javax.swing.JLabel sc_amt;
    private javax.swing.JScrollPane scroll;
    private button.Button search_records;
    private javax.swing.JLabel side_logo;
    private test.RoundPanel sidebar;
    private javax.swing.JLabel sign;
    private view.custom.textarea.TextArea textArea1;
    private view.custom.textarea.TextAreaScroll textAreaScroll1;
    private javax.swing.JLabel to;
    private javax.swing.JLabel top_date;
    private javax.swing.JLabel total;
    private textfield.TextField txt_Amount;
    private textfield.TextField txt_bank;
    private textfield.TextField txt_cheque;
    private textfield.TextField txt_course;
    private textfield.TextField txt_in_words;
    private textfield.TextField txt_receipt_no;
    private textfield.TextField txt_received_from;
    private textfield.TextField txt_sc_amt;
    private textfield.TextField txt_tdate;
    private textfield.TextField txt_total;
    private textfield.TextField txt_vat;
    private javax.swing.JLabel vat;
    private button.Button view_all_records;
    private button.Button view_courses;
    private button.Button view_report;
    private javax.swing.JPanel workng_panel;
    // End of variables declaration//GEN-END:variables
}
